version: '3.8'

services:
    rru_fdd:
        image: oai-enb:latest
        privileged: true
        container_name: lte-b200-rru-fdd-05Mhz-tm1
        network_mode: "host"
        environment:
            USE_B2XX: 'yes'
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time,line_num,function
        volumes:
            - ../../conf_files/enb-rru.band7.usrpb210.tm1.conf:/opt/oai-enb/etc/enb.conf
            - /dev:/dev
        healthcheck:
            # pgrep does NOT work
            test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    rcc_fdd:
        image: oai-enb:latest
        privileged: true
        container_name: lte-b200-rcc-fdd-05Mhz-tm1
        network_mode: "host"
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time,line_num,function
        volumes:
            - ../../conf_files/enb-rcc.band7.25prb.tm1.if4p5.conf:/opt/oai-enb/etc/enb.conf
        healthcheck:
            # pgrep does NOT work
            test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
